### ISSUE TITLE
Localized Relaunch button

### ISSUE THREAD

**Issue by Dejal** [redsweater/RSAppMovementMonitor#1]
Welcome to the first issue!

You cache the localized strings to prevent problems after the app is moved, but don't cache the Relaunch button's localized string. Not as critical, but probably still worthwhile?

**Comment by danielpunkass** [comment]
Thanks! I know somebody is working on this already so I'll alert them to the fact there is an issue. Good eye!

**Comment by danielpunkass** [comment]
Fixed by #3
